# See Tools/build/Makefile_template for more information
SDK_DIR = $(realpath $(CURDIR)/../../../../..)

BOARD = EVU_BA_2_5
CORE_NUM = CORE_1

MEM_REG_ROM_OFFSET = 0x20000# 128K
MEM_REG_ROM_SIZE = 0x1FC00# 127K

MEM_REG_RAM_OFFSET = 0x4000# 16K
MEM_REG_RAM_SIZE = 0x4000# 16K

# Include the main makefile
include $(SDK_DIR)/Tools/build/common.mk
