# See Tools/build/Makefile_template for more information
SDK_DIR = $(realpath $(CURDIR)/../..)

CSRC += $(SDK_DIR)/Drivers/HAL/Src/bmcu_cru.c
CSRC += $(SDK_DIR)/Drivers/HAL/Src/bmcu_gpio.c
CSRC += $(SDK_DIR)/Drivers/HAL/Src/bmcu_uart.c

# Include the main makefile
include $(SDK_DIR)/Tools/build/common.mk
